apiVersion: kctrl.carvel.dev/v1alpha1
kind: PackageRepositoryBuild
metadata:
  creationTimestamp: "2023-07-07T14:32:30Z"
  name: tanzu-handy-packages.tanzuplatform.com
spec:
  export:
    imgpkgBundle:
      image: us-east5-docker.pkg.dev/pa-rvanvoorhees/carvel/imgpkg/tanzu-handy-packages
