apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  creationTimestamp: null
  name: tanzu-ai-accelerators.tanzuplatform.com.0.0.1
spec:
  refName: tanzu-ai-accelerators.tanzuplatform.com
  releasedAt: "2023-07-07T15:37:26Z"
  template:
    spec:
      deploy:
      - kapp: {}
      fetch:
      - imgpkgBundle:
          image: us-east5-docker.pkg.dev/pa-rvanvoorhees/carvel/imgpkg/tanzu-handy-packages@sha256:ebc17db6f0a36fccd67089b8cbad421771d8fde972d0e54adacdbcc6ba852586
      template:
      - ytt:
          paths:
          - ./config
      - kbld:
          paths:
          - '-'
          - .imgpkg/images.yml
  valuesSchema:
    openAPIv3:
      default: null
      nullable: true
  version: 0.0.1
