apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  creationTimestamp: null
  name: tanzu-ai-accelerators.tanzuplatform.com.0.1.1
spec:
  refName: tanzu-ai-accelerators.tanzuplatform.com
  releasedAt: "2023-07-10T16:37:08Z"
  template:
    spec:
      deploy:
      - kapp: {}
      fetch:
      - imgpkgBundle:
          image: us-east5-docker.pkg.dev/pa-rvanvoorhees/carvel/imgpkg/tanzu-handy-packages@sha256:0d5fba989c49a2a6531a45bf463f0aa52e7bfdcb95a108034c81ec14dfd49f10
      template:
      - ytt:
          paths:
          - ./config
      - kbld:
          paths:
          - '-'
          - .imgpkg/images.yml
  valuesSchema:
    openAPIv3: null
  version: 0.1.1
