apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  creationTimestamp: null
  name: tanzu-ai-accelerators.tanzuplatform.com.0.0.0+build.1688740136
spec:
  refName: tanzu-ai-accelerators.tanzuplatform.com
  releasedAt: "2023-07-07T14:30:54Z"
  template:
    spec:
      deploy:
      - kapp: {}
      fetch:
      - imgpkgBundle:
          image: us-east5-docker.pkg.dev/pa-rvanvoorhees/carvel/imgpkg/tanzu-handy-packages@sha256:1b6d721e97f2435ff46182e64f099731e13917a351e25406c0f0639b562fd120
      template:
      - ytt:
          paths:
          - ./config
      - kbld:
          paths:
          - '-'
          - .imgpkg/images.yml
  valuesSchema:
    openAPIv3:
      default: null
      nullable: true
  version: 0.0.0+build.1688740136
